# Generated by Django 4.0.3 on 2025-08-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_collectingdb_promoperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingdb',
            name='body',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='address001',
            field=models.CharField(max_length=120, null=True, verbose_name='주소'),
        ),
    ]
