# Generated by Django 4.0.3 on 2025-08-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_collectingdb_body_alter_collectingdb_address001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingdb',
            name='cate001',
        ),
    ]
